[build]
default-target = "aarch64-unknown-linux-gnu"

[build.dockerfile]
file = "./docker/Dockerfile"
context = "./docker"

[build.env]
passthrough = [
  "PKG_CONFIG=/usr/bin/aarch64-linux-gnu-pkg-config",
]
