[package]
name = "mechanum-chassis-node"
version = "0.1.0"
edition = "2021"

[dependencies]
robotica = { workspace = true }
mechanum-protos = { path = "../../mechanum-protos", version = "0.1.0" }
anyhow = { workspace = true }
tokio = { workspace = true }
