include!(concat!(env!("OUT_DIR"), "/mechanum.rs"));

/// Contains the bytes of the file descriptor set generated by `prost_build`.
pub const DESCRIPTOR_SET_BYTES: &[u8] =
    include_bytes!(concat!(env!("OUT_DIR"), "/file_descriptor_set.bin"));
