[package]
name = "motor-controller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
i2cdev = "0.6.1"
int-enum = "1.1.2"
thiserror = "1.0.63"
